stages:
  data_ingestion:
    cmd: python src/cnn_classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnn_classifier/pipeline/stage_01_data_ingestion.py
      - src/cnn_classifier/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/chicken-diseases-image-dataset

  prepare_base_model:
    cmd: python src/cnn_classifier/pipeline/stage02_prepare_base_model.py
    deps:
      - src/cnn_classifier/pipeline/stage02_prepare_base_model.py
      - src/cnn_classifier/components/prepare_base_model.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model/base_model.h5
      - artifacts/prepare_base_model/updated_base_model.h5

  prepare_callbacks:
    cmd: python src/cnn_classifier/pipeline/stage03_create_callbacks.py
    deps:
      - src/cnn_classifier/pipeline/stage03_create_callbacks.py
      - src/cnn_classifier/components/prepare_callbacks.py
      - config/config.yaml
    outs:
      - artifacts/prepare_callbacks

  training:
    cmd: python src/cnn_classifier/pipeline/stage_04_training.py
    deps:
      - src/cnn_classifier/pipeline/stage_04_training.py
      - src/cnn_classifier/components/training.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion/chicken-diseases-image-dataset
      - artifacts/prepare_base_model/updated_base_model.h5
      - artifacts/prepare_callbacks
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/trained_model.h5

  evaluation:
    cmd: python src/cnn_classifier/pipeline/stage_05_evaluation.py
    deps:
      - src/cnn_classifier/pipeline/stage_05_evaluation.py
      - src/cnn_classifier/components/evaluation.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion/chicken-diseases-image-dataset
      - artifacts/training/trained_model.h5
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
    metrics:
      - scores.json:
          cache: false
